### ISSUE TITLE
Compositor crashes when "abruptly and normally" closing VLC

### ISSUE THREAD

**Issue by FGD-Garuda** [tildearrow/kwin-lowlatency#118]
Hello and thanks for this improved kwin, I can play smoothly 4k@60hz with your unredirection setting on full screen videos.

I recently upgraded to 5.23.4. When I play a VLC video (the mode with just one window opened and the controls showing right under the video in that same window) and I do what everyone does since 1000 years which is hit the close button while playing, it then crashes kwin. Thanks to your option to restart the compositor without disabling it.

Now if I uninstall kwin-lowlatency and install same version (5.23.4) of kwin, it does not crash at all.

I am not sure what trace log to provide, but I did come across some info here https://forum.videolan.org/viewtopic.php?f=13&t=149762&start=25

I have a Nvidia GTX1650 with 495 drivers, of course I can test this with a different driver version if need be or a different video player/video mode, however my question is not who is responsible but rather why. Why is it that with kwin-lowlatency is crashes and not the standard kwin, what's different between the 2 so it does that?

What is mentioned on the above URL is true, if I stop the video and then hit the close button, kwin-lowlatency does not crash, but it's also not intuitive to stop the video before closing, so many times I forget and it crashes.

Thanks

**Comment by tildearrow** [comment]
Upon crash there should be a sad face in the notification area. If you click on it you'll open a "sorry" dialog.
Click on Developer Information and then provide the backtrace that appears.

**Comment by FGD-Garuda** [comment]
Yeah I remember that sad face icon notification back when I was using Kubuntu. However I do not get any notification at all right now. Not sure if it's disabled by Garuda team or the crash does not log anything. I enabled all pop-up notification, marking to systray and logging to a specific file in the Notifications settings page in System Settings but nothing shows anywhere.

So what I did is I was hitting `journalctl -b | grep 'kwin'` a couple of times while the video is playing, to make sure I don't get totally unrelated information and then I closed the video from VLC and immediately hit another `journalctl -b | grep 'kwin'`. It's not worth much but here's what I got:

> Dec 05 15:49:10 Garuda kwin_x11[38221]: kwin_core: Failed to focus 0x4200001 (error 3)
Dec 05 15:49:10 Garuda kwin_x11[38221]: ASSERT: "d->m_texture" in file /home/main-builder/pkgwork/src/kwin-lowlatency/src/libkwineffects/kwingltexture.cpp, line 440
Dec 05 15:49:11 Garuda ananicy-cpp[671]: [2021-12-05 15:49:11.965] [info] kwin_x11(54350)
Dec 05 15:49:11 Garuda ananicy-cpp[671]: [2021-12-05 15:49:11.968] [info] kwin_x11(54351)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.007] [info] kwin_x11(54352)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.008] [info] kwin_x11(54352)
Dec 05 15:49:12 Garuda audit[38221]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 pid=38221 comm="kwin_x11" exe="/usr/bin/kwin_x11" sig=6 res=1
Dec 05 15:49:12 Garuda kwin_x11[54351]: Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.219] [info] kwin_x11(54363)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.219] [info] kwin_x11(54363)
Dec 05 15:49:12 Garuda kwin_x11[54351]: Icon theme "gnome" not found.
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.238] [info] kwin_x11(54364)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.238] [info] kwin_x11(54364)
Dec 05 15:49:12 Garuda kwin_x11[54351]: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5089:46: this compose sequence is a duplicate of another; skipping line
Dec 05 15:49:12 Garuda kwin_x11[54351]: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5091:48: this compose sequence is a duplicate of another; skipping line
Dec 05 15:49:12 Garuda kwin_x11[54351]: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5093:48: this compose sequence is a duplicate of another; skipping line
Dec 05 15:49:12 Garuda kwin_x11[54351]: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5097:47: this compose sequence is a duplicate of another; skipping line
Dec 05 15:49:12 Garuda kwin_x11[54351]: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5099:46: this compose sequence is a duplicate of another; skipping line
Dec 05 15:49:12 Garuda kwin_x11[54351]: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5107:48: this compose sequence is a duplicate of another; skipping line
Dec 05 15:49:12 Garuda kwin_x11[54351]: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5111:46: this compose sequence is a duplicate of another; skipping line
Dec 05 15:49:12 Garuda kwin_x11[54351]: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5113:46: this compose sequence is a duplicate of another; skipping line
Dec 05 15:49:12 Garuda kwin_x11[54351]: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5117:45: this compose sequence is a duplicate of another; skipping line
Dec 05 15:49:12 Garuda kwin_x11[54351]: kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5120:46: this compose sequence is a duplicate of another; skipping line
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.324] [info] kwin_x11(54365)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.324] [info] kwin_x11(54365)
Dec 05 15:49:12 Garuda kwin_x11[54351]: Module 'org.kde.kwin.decoration' does not contain a module identifier directive - it cannot be protected from external registrations.
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.449] [info] kwin_x11(55458)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.449] [info] kwin_x11(55458)
Dec 05 15:49:12 Garuda dbus-daemon[3657]: [session uid=1000 pid=3657] Activating service name='org.kde.KSplash' requested by ':1.95' (uid=1000 pid=54351 comm="/usr/bin/kwin_x11 --crashes 0 ")
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.479] [info] kwin_x11(55535)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.479] [info] kwin_x11(55535)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.517] [info] kwin_x11(55536)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.518] [info] kwin_x11(55536)
Dec 05 15:49:12 Garuda kwin_x11[54351]: qml: FORCE-BLUR: starting the script
Dec 05 15:49:12 Garuda kwin_x11[54351]: qml: [""]
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.532] [info] kwin_x11(55537)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.533] [info] kwin_x11(55538)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.535] [info] kwin_x11(55539)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.537] [info] kwin_x11(55540)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.559] [info] kwin_x11(55541)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.560] [info] kwin_x11(55542)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.562] [info] kwin_x11(55543)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.564] [info] kwin_x11(55544)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.566] [info] kwin_x11(55545)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.568] [info] kwin_x11(55546)
Dec 05 15:49:12 Garuda ananicy-cpp[671]: [2021-12-05 15:49:12.569] [info] kwin_x11(55547)
Dec 05 15:49:12 Garuda kwin_x11[54351]: kwin_core: XCB error: 10 (BadAccess), sequence: 2896, resource id: 480, major code: 142 (Composite), minor code: 2 (RedirectSubwindows)
Dec 05 15:49:13 Garuda systemd-coredump[54354]: Process 38221 (kwin_x11) of user 1000 dumped core.
Found module kwin5_aurorae.so with build-id: 50e5895fadbef332d78e5115ea889687baace538
Found module libkwinxrenderutils.so.13 with build-id: 281a6052d6e6744c93cee4747b0d6473f2596d6d
Found module libkwinglutils.so.13 with build-id: 61951fb9fcf26a6bf52f2a4af51230f2124c225a
Found module libkwineffects.so.13 with build-id: 3b3599f71463ff7d8a782bac5a996d2ea39c3f03
Found module libkwin4_effect_builtins.so.1 with build-id: 4aee6b029a57132562d71f374d4fa83eabe2d9ff
Found module libkwin.so.5 with build-id: 3c1609052cc58245056b266fa4c8fee02a921610
Found module kwin_x11 with build-id: 957a6636a64b08439c6f1fed9f0c5da7c45bd67d
#7  0x00007f743b01624d n/a (libkwinglutils.so.13 + 0xb24d)
#8  0x00007f743b01d7f8 _ZN4KWin9GLTextureC2Ejiiib (libkwinglutils.so.13 + 0x127f8)
#11 0x00007f743cc6e5dd _ZN4KWin14DecorationItem10preprocessEv (libkwin.so.5 + 0x1575dd)
#13 0x00007f743cbfbfc3 _ZN4KWin8Toplevel12windowClosedEPS0_PNS_7DeletedE (libkwin.so.5 + 0xe4fc3)
#14 0x00007f743cdc3c4a _ZN4KWin9X11Client13destroyClientEv (libkwin.so.5 + 0x2acc4a)
#15 0x00007f743cc979c7 _ZN4KWin9X11Client16unmapNotifyEventEP24xcb_unmap_notify_event_t (libkwin.so.5 + 0x1809c7)
#16 0x00007f743cc9af74 _ZN4KWin9X11Client11windowEventEP19xcb_generic_event_t (libkwin.so.5 + 0x183f74)
#17 0x00007f743cc9b2cb _ZN4KWin9Workspace14workspaceEventEP19xcb_generic_event_t (libkwin.so.5 + 0x1842cb)
#24 0x00005599a180d541 n/a (kwin_x11 + 0x7541)
#26 0x00005599a180da7e n/a (kwin_x11 + 0x7a7e)


Quite possible all this has nothing to do with the crash itself, I cannot tell.

I googled around but could not find where kwin stores its backtrace log files. I'm kinda stuck. Maybe I should post on the Garuda forums, that's another option, someone or the team could tell me what I need to do to acces such trace... or maybe I could use `journalctl` but with a better command than the one I issued.

I hate when I cannot provide clean data.

:(

**Comment by tildearrow** [comment]
Let's try to acquire a better backtrace.

Open an SSH connection to the machine (yes) and type:
```
gdb kwin_x11
```

This engages a debugger. After that type:
```
run --replace
```

This will start a debugging session of KWin.

Crash it and then the display will freeze and the debugger will say something about SIGSEGV or SIGABRT. Type:
```
backtrace
```

then

```
q
```

This will output a backtrace which should come in handy.

**Comment by tildearrow** [comment]
Adding to this, I see an error when redirecting subwindows.... Hmmmm....
I should try adding the error check again just in case but last time I did it didn't work...

**Comment by FGD-Garuda** [comment]
Wow I didn't know it was possible to ssh a machine to itself.

But gdb failed. Here's what I did:

```
λ systemctl start sshd.service
λ ssh user@localhost
```

Entered PW of course and I was in

`λ DISPLAY=:0 gdb kwin_x11` Came across your post to do that! [https://github.com/tildearrow/kwin-lowlatency/issues/35](url)

Then

`λ run --replace`

That replaced kwin I saw it restarting. I then opened a video and when I hit close button, the entire computer locked up with absolutely nothing showing on the screen other than how the screen was at the exact moment it froze. Only the mouse was still moving but no button. It disappeared as soon as I hit ALT key.
Luckily I could TTY into a 2nd session but nothing was starting other than Conky (even no wallpaper). I then TTYed to a 3rd session and rebooted.

Something there doesn't want me to debug. :)
On the other hand it's not funny. lol

**Comment by tildearrow** [comment]
It is intended to freeze. It means it crashed.

Try again, but when it freezes immediately check the debugger in your SSH session. It should say something (if it doesn't you can hit Ctrl-C and you will jump back to the debugger).
Then you can type `backtrace` from there.

Also, there should be some "FOR CRASH" messages that might come in handy.

One more footnote: You have to run the debugger on a separate computer (or a phone with an SSH app installed), or at least a different TTY...

**Comment by FGD-Garuda** [comment]
> One more footnote: You have to run the debugger on a separate computer (or a phone with an SSH app installed), or at least a different TTY...

That's probably why. I am on my localhost connected to localhost on the same TTY. It freezes before showing any debug info and CTRL-C, X, Q, BREAK, etc. don't do a thing.

I'll see what other device I can use, I wonder if Chromebook would work, I've got 4 options, 2nd TTY on same machine, Chromebook, Windows 11 and Android phone (version 12). One of these will certainly work. I can test TTY right now, if it fails it'll take me a bit longer to move on another device, but I will.

**Comment by tildearrow** [comment]
...yyyyyup. If you don't have another device you can use a TTY instead.

**Comment by FGD-Garuda** [comment]
It seems I have issues with TTYs. Even when TTY1 is working cleanly, when I start TTY2 only Conky launches. Back to TTY1 and compositor acts strangely, lost functions and no window border.

So I'll move on another device to ssh.

**Comment by tildearrow** [comment]
That doesn't seem normal, but I'll wait.

**Comment by ptr1337** [comment]
Could be also a problem from the upstream KDE since it haves many bugs right now. 

https://www.phoronix.com/scan.php?page=news_item&px=KDE-Starts-December-2021

**Comment by tildearrow** [comment]
@ptr1337 It's definitely not. This is an issue with unredirection, so it is not a bug in vanilla KWin.

**Comment by FGD-Garuda** [comment]
> That doesn't seem normal [...].

 

Nope it's not. lol There seems to be conflicting PIDs when second TTY starts in X, maybe it's a Garuda thing, but I got a bigger dog to chase before I look into that one. :)

 

I will be able to perform more SSH stuff tonight, in the meantime I realized I don't understand well enough how that principle works. I googled a few things but it was difficult to find something related to what I'm trying to do here and what I'm trying to understand.

 

Maybe someone can help me understand a bit more?

 

Here's where I'm confused:

 

- Can I actually debug only from a command line that is in a second TTY or machine? My current TTY issue is only when I `startx`, maybe I don't need to startx at all?

- If I can debug from command line in TTY2, how do I ensure I actually SSH to TTY1? Using `screen` or `ttylog` or some other method?

- Once I ensure I connect to TTY1 (or to the machine if I am using a second machine to SSH), what command should I use to run gdb from that TTY2/machine#2? `DISPLAY=:0 gdb kwin_x11` `DISPLAY=:1 gdb kwin_x11` `gdb kwin_x11` Something else?

- How can `run --replace` works if I am in a terminal mode without X graphically loaded? I believe kwin is not loaded also in that situation so I don't understand how it works.

All that being said, I was able to log into machine#1 from my Chromebook through SSH. So I could debug there, as long I use the proper gdb commands, should they be different then those from a few posts above. And I believe I don't need to startx.
 

Thank you very much!

**Comment by tildearrow** [comment]
> Nope it's not. lol There seems to be conflicting PIDs when second TTY starts in X, maybe it's a Garuda thing, but I got a bigger dog to chase before I look into that one. :)

First of all, you do not need to start another X session in order to debug KWin.

> I will be able to perform more SSH stuff tonight, in the meantime I realized I don't understand well enough how that principle works. I googled a few things but it was difficult to find something related to what I'm trying to do here and what I'm trying to understand.

Got it... Basically SSH is a thing that allows you to remotely connect to your machine.

> * Can I actually debug only from a command line that is in a second TTY or machine? My current TTY issue is only when I `startx`, maybe I don't need to startx at all?

Yes, you can. But please do not type `startx` under any circumstances. You are supposed to debug the main session, not create a new one. I don't know where were you told to do that.

> * If I can debug from command line in TTY2, how do I ensure I actually SSH to TTY1? Using `screen` or `ttylog` or some other method?

It appears you didn't understand my last sentence, so let me phrase it clearly.

SSH does not hook to TTY1 or something. It creates a virtual terminal (when you type `who` you will see something like `pts/0`).

> * Once I ensure I connect to TTY1 (or to the machine if I am using a second machine to SSH), what command should I use to run gdb from that TTY2/machine#2? `DISPLAY=:0 gdb kwin_x11` `DISPLAY=:1 gdb kwin_x11` `gdb kwin_x11` Something else?

`DISPLAY=:0 gdb kwin_x11` should do the job and start the debugger correctly.

> * How can `run --replace` works if I am in a terminal mode without X graphically loaded? I believe kwin is not loaded also in that situation so I don't understand how it works.

Because you set the DISPLAY environment variable.

> All that being said, I was able to log into machine#1 from my Chromebook through SSH. So I could debug there, as long I use the proper gdb commands, should they be different then those from a few posts above. And I believe I don't need to startx.

Yep, correct. Again, do not ever type `startx`. There is no need. We are debugging the main desktop session, not creating another.

**Comment by tildearrow** [comment]
In a summary, here is what you need to do in order to acquire a backtrace:

1. SSH to your machine
2. Type `DISPLAY=:0 gdb kwin_x11` on the SSH session.
3. It will say `(gdb)`. Type `run --replace`.
4. Crash it.
5. Go back to the SSH session and you will see that the debugger has stopped and you are back to the `(gdb)` prompt.
6. Type `backtrace`. This will let you see the backtrace.
7. Type `q` and then `y` to quit the debugger.

**Comment by FGD-Garuda** [comment]
Yes! Got it! I understand better now what I was doing. :)

Here ya go:

```
(gdb) run --replace
Starting program: /usr/bin/kwin_x11 --replace
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffefaf5640 (LWP 76068)]
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
[New Thread 0x7fffe7eff640 (LWP 76069)]
[New Thread 0x7fffe76fe640 (LWP 76070)]
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5089:46: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5091:48: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5093:48: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5097:47: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5099:46: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5107:48: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5111:46: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5113:46: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5117:45: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5120:46: this compose sequence is a duplicate of another; skipping line
[New Thread 0x7fffe6b1d640 (LWP 76073)]
Module 'org.kde.kwin.decoration' does not contain a module identifier directive - it cannot be protected from external registrations.
Icon theme "gnome" not found.
[New Thread 0x7fffe4a8f640 (LWP 76074)]
[New Thread 0x7fffd77bf640 (LWP 76078)]
OpenGL vendor string:                   NVIDIA Corporation
OpenGL renderer string:                 NVIDIA GeForce GTX 1650/PCIe/SSE2
OpenGL version string:                  3.1.0 NVIDIA 495.44
OpenGL shading language version string: 1.40 NVIDIA via Cg compiler
Driver:                                 NVIDIA
Driver version:                         495.44
GPU class:                              Unknown
OpenGL version:                         3.1
GLSL version:                           1.40
X server version:                       1.21.1
Linux kernel version:                   5.15.3
Requires strict binding:                no
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
[New Thread 0x7fffd6c31640 (LWP 76079)]
[New Thread 0x7fffd60ee640 (LWP 76080)]
qml: FORCE-BLUR: starting the script
qml: [""]
[Detaching after fork from child process 76081]
[Detaching after fork from child process 76082]
[Detaching after fork from child process 76083]
[Detaching after fork from child process 76084]
[Detaching after fork from child process 76085]
[Detaching after fork from child process 76086]
[Detaching after fork from child process 76087]
kwin_core: XCB error: 10 (BadAccess), sequence: 2119, resource id: 480, major code: 142 (Composite), minor code: 2 (RedirectSubwindows)
[New Thread 0x7fffb37b6640 (LWP 76090)]
[Thread 0x7fffd77bf640 (LWP 76078) exited]
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3100, resource id: 60817429, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3105, resource id: 60817430, major code: 18 (ChangeProperty), minor code: 0
[Detaching after fork from child process 76488]
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3467, resource id: 67108865, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3557, resource id: 67108865, major code: 3 (GetWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 3558, resource id: 67108865, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3559, resource id: 67108865, major code: 8 (MapWindow), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3560, resource id: 67108865, major code: 12 (ConfigureWindow), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4029, resource id: 62914568, major code: 18 (ChangeProperty), minor code: 0
kwin_core: Failed to focus 0x4000001 (error 3)
kwin_core: Failed to focus 0x4000001 (error 3)
kwin_core: Failed to focus 0x4000001 (error 3)
ASSERT: "d->m_texture" in file /home/main-builder/pkgwork/src/kwin-lowlatency/src/libkwineffects/kwingltexture.cpp, line 440

Thread 1 "kwin_x11" received signal SIGABRT, Aborted.
0x00007ffff6270d22 in raise () from /usr/lib/libc.so.6
(gdb) backtrace
#0  0x00007ffff6270d22 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff625a862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff6efb910 in  () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff6efacf5 in qt_assert_x(char const*, char const*, char const*, int) () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff60b124d in  () at /usr/lib/libkwinglutils.so.13
#5  0x00007ffff60b87f8 in KWin::GLTexture::GLTexture(unsigned int, int, int, int, bool) () at /usr/lib/libkwinglutils.so.13
#6  0x00007fffe40710f3 in  () at /usr/lib/qt/plugins/org.kde.kwin.scenes/KWinSceneOpenGL.so
#7  0x00007fffe407876d in  () at /usr/lib/qt/plugins/org.kde.kwin.scenes/KWinSceneOpenGL.so
#8  0x00007ffff7d095dd in KWin::DecorationItem::preprocess() () at /usr/lib/libkwin.so.5
#9  0x00007ffff715b7cb in  () at /usr/lib/libQt5Core.so.5
#10 0x00007ffff7c96fc3 in KWin::Toplevel::windowClosed(KWin::Toplevel*, KWin::Deleted*) () at /usr/lib/libkwin.so.5
#11 0x00007ffff7e5ec4a in KWin::X11Client::destroyClient() () at /usr/lib/libkwin.so.5
#12 0x00007ffff7d329c7 in KWin::X11Client::unmapNotifyEvent(xcb_unmap_notify_event_t*) () at /usr/lib/libkwin.so.5
#13 0x00007ffff7d35f74 in KWin::X11Client::windowEvent(xcb_generic_event_t*) () at /usr/lib/libkwin.so.5
#14 0x00007ffff7d362cb in KWin::Workspace::workspaceEvent(xcb_generic_event_t*) () at /usr/lib/libkwin.so.5
#15 0x00007ffff71218bf in QAbstractEventDispatcher::filterNativeEvent(QByteArray const&, void*, long*) () at /usr/lib/libQt5Core.so.5
#16 0x00007fffefb99b03 in QXcbConnection::handleXcbEvent(xcb_generic_event_t*) () at /usr/lib/libQt5XcbQpa.so.5
#17 0x00007fffefb9b149 in QXcbConnection::processXcbEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5XcbQpa.so.5
#18 0x00007fffefbc23ae in  () at /usr/lib/libQt5XcbQpa.so.5
#19 0x00007ffff7122d8c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#20 0x00007ffff712b2f4 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#21 0x000055555555b541 in  ()
#22 0x00007ffff625bb25 in __libc_start_main () at /usr/lib/libc.so.6
#23 0x000055555555ba7e in  ()
(gdb) q
A debugging session is active.

        Inferior 1 [process 75841] will be killed.
```

**Comment by tildearrow** [comment]
Hmmm... that looks odd. Can you try disabling unredirection (System Settings > Display and Monitor > Compositor > Enable full-screen unredirection (X11)) and see if it still reproduces?
If so, then disable the force blur script and try reproducing again. Doesn't look like unredirection might be the cause, but not sure.

**Comment by FGD-Garuda** [comment]
You are good.

> Can you try disabling unredirection (System Settings > Display and Monitor > Compositor > Enable full-screen unredirection (X11)) and see if it still reproduces?

It does reproduce with that cool feature disabled.

> ... then disable the force blur script and try reproducing again.

WORKS!
With very specifically KDE's "Blur" effect (not the one of KVantum!) in System Settings > Workspace Behavior > Desktop Effects turned OFF, nothing crashes. 

Not an option for me to disable it, though, as Garuda's theme is heavily based on blur and translucency, but maybe for some people it is an acceptable workaround.

**Comment by FGD-Garuda** [comment]
Hi, I see this has been tagged as a BUG, maybe it was there last month I didn't pay attention.
Is it really confirmed as a bug?

Either way lemme know if you need more data to troubleshoot. :)


Thanks!

**Comment by HerrCraziDev** [comment]
I do confirm having the exact same bug, on Arch, with an Nvidia GTX 1660 TI.
Same symptoms and disabling the Force Blur effect also solves it.
